# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'glosarium.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from resource import glosarium
# import glosarium_sniffing



class Ui_Glosarium_Protokol(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        qss3 = open('../resource/styleGlosariumProtokol.qss').read()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #90caf9, stop:1 #a6d4fa);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Lato Heavy")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sniff_app = QtWidgets.QPushButton(self.frame_3)
        self.sniff_app.setStyleSheet(qss3)
        self.sniff_app.setDefault(False)
        self.sniff_app.setFlat(False)
        self.sniff_app.setObjectName("sniff_app")
        self.verticalLayout_2.addWidget(self.sniff_app)
        self.sekilas_protokol = QtWidgets.QPushButton(self.frame_3)
        self.sekilas_protokol.setStyleSheet(qss3)
        self.sekilas_protokol.setObjectName("sekilas_protokol")
        self.verticalLayout_2.addWidget(self.sekilas_protokol)
        spacerItem = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem)
        self.kembaliBtn = QtWidgets.QPushButton(self.frame_3)
        self.kembaliBtn.setStyleSheet(qss3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resource/1x/Asset 2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kembaliBtn.setIcon(icon)
        self.kembaliBtn.setObjectName("kembaliBtn")
        self.verticalLayout_2.addWidget(self.kembaliBtn)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.arp_tb = QtWidgets.QWidget()
        self.arp_tb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.arp_tb.setObjectName("arp_tb")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.arp_tb)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.arp_tb)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1023, 603))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.arp_tb, "")
        self.icmp_tb = QtWidgets.QWidget()
        self.icmp_tb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.icmp_tb.setObjectName("icmp_tb")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.icmp_tb)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.icmp_tb)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(-9, 0, 1019, 603))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_8.addWidget(self.scrollArea_3)
        self.tabWidget.addTab(self.icmp_tb, "")
        self.udp_tb = QtWidgets.QWidget()
        self.udp_tb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.udp_tb.setObjectName("udp_tb")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.udp_tb)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.udp_tb)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 1027, 603))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_10.addWidget(self.scrollArea_4)
        self.tabWidget.addTab(self.udp_tb, "")
        self.dns_tb = QtWidgets.QWidget()
        self.dns_tb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dns_tb.setObjectName("dns_tb")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dns_tb)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.dns_tb)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.tabWidget.addTab(self.dns_tb, "")
        self.tcp_tb = QtWidgets.QWidget()
        self.tcp_tb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tcp_tb.setObjectName("tcp_tb")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tcp_tb)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.tcp_tb)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5)
        self.tabWidget.addTab(self.tcp_tb, "")
        self.dhcp_tb = QtWidgets.QWidget()
        self.dhcp_tb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dhcp_tb.setObjectName("dhcp_tb")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.dhcp_tb)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.dhcp_tb)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        self.tabWidget.addTab(self.dhcp_tb, "")
        self.http_tb = QtWidgets.QWidget()
        self.http_tb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.http_tb.setObjectName("http_tb")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.http_tb)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_7 = QtWidgets.QLabel(self.http_tb)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_13.addWidget(self.label_7)
        self.tabWidget.addTab(self.http_tb, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Glosarium - Sekilas Tentang Protokol"))
        self.label.setText(_translate("MainWindow", "Glosarium"))
        self.sniff_app.setText(_translate("MainWindow", "Istilah Jaringan"))
        self.sekilas_protokol.setText(_translate("MainWindow", "Sekilas Tentang Protokol"))
        self.kembaliBtn.setText(_translate("MainWindow", "Kembali"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/packet_arp/arp.PNG\"/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.arp_tb), _translate("MainWindow", "ARP"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/packet_icmp/icmp.PNG\"/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.icmp_tb), _translate("MainWindow", "ICMP"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/udp/udp.PNG\"/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.udp_tb), _translate("MainWindow", "UDP"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/dns/dns.PNG\"/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dns_tb), _translate("MainWindow", "DNS"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/tcp/tcp.PNG\"/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tcp_tb), _translate("MainWindow", "TCP"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/dhcp/dhcp.PNG\"/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dhcp_tb), _translate("MainWindow", "DHCP"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/http/http.PNG\"/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.http_tb), _translate("MainWindow", "HTTP"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Glosarium_Protokol()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
