# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'glosarium_istilah.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
# import glosarium_proto


class Ui_Glosarium_Istilah(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        qss2_file = open('../resource/styleGlosarium.qss').read()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #90caf9, stop:1 #a6d4fa);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Lato Heavy")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sniff_app = QtWidgets.QPushButton(self.frame_3)
        self.sniff_app.setStyleSheet(qss2_file)
        self.sniff_app.setDefault(False)
        self.sniff_app.setFlat(False)
        self.sniff_app.setObjectName("sniff_app")
        self.verticalLayout_2.addWidget(self.sniff_app)
        self.sekilas_protokol = QtWidgets.QPushButton(self.frame_3)
        self.sekilas_protokol.setStyleSheet(qss2_file)
        self.sekilas_protokol.setObjectName("sekilas_protokol")
        self.verticalLayout_2.addWidget(self.sekilas_protokol)
        spacerItem = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem)
        self.kembaliBtn = QtWidgets.QPushButton(self.frame_3)
        self.kembaliBtn.setStyleSheet(qss2_file)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resource/1x/Asset 2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kembaliBtn.setIcon(icon)
        self.kembaliBtn.setObjectName("kembaliBtn")
        self.verticalLayout_2.addWidget(self.kembaliBtn)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 589, 464))
        self.scrollAreaWidgetContents.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(14)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(68)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Glosarium - Istilah Jaringan"))
        self.label.setText(_translate("MainWindow", "Glosarium"))
        self.sniff_app.setText(_translate("MainWindow", "Istilah Jaringan"))
        self.sekilas_protokol.setText(_translate("MainWindow", "Sekilas Tentang Protokol"))
        self.kembaliBtn.setText(_translate("MainWindow", "Kembali"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Istilah"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Penjelasan"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "IP Address"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Sebaris angka yang dimiliki oleh sebuah perangkat komputer yang digunakan sebagai penanda suatu perangkat agar lebih mudah dihubungi dalam suatu jaringan "))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "Sniffing"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "Sniffing adalah proses monitoring semua paket data yang lewat dalam suatu jaringan. Kegiatan ini umumnya dilakukan oleh network administrator untuk menganalisis apa yang sedang terjadi pada jaringan"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "Interface"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "Sebuah titik interkoneksi yang menghubungkan antara sebuah perangkat komputer dengan jaringan komputer. Umumnya Interface dapat berupa perangkat keras seperti Network Interface Card Wifi namun terkadang juga dapat berupa perangkat lunak seperti loopback interface"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "Protokol"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "Aturan pengiriman dalam jaringan komputer yang harus ditaati oleh pihak pengiriman dan penerima agar dapat bertukar informasi meskipun memiliki sistem yang berbeda"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "Wi-Fi"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "Teknologi jaringan yang biasa digunakan untuk membuat jaringan secara nirkabel"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "MAC Address"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("MainWindow", "Merupakan singkatan dari Media Access Control adalah sebuah metode identifikasi unik yang ditempatkan di setiap network interface controller untuk digunakan sebagai network address dalam komunikasi jaringan komputer"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "SOA"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("MainWindow", "Singkatan dari Start Of Authority, adalah sebuah paket DNS yang berisikan informasi mengenai otoritas yang mengatur sebuah domain name"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "SYN"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("MainWindow", "Singkatan dari Synchronize, adalah sebuah TCP packet yang biasa dikirim untuk meminta koneksi baru dibuat antar dua perangkat. Jika paket SYN diterima oleh perangkat kedua maka perangkat kedua akan mengirimkan pesan SYN/ACK kepada perangkat pengirim sebelumnya. "))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "ACK"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("MainWindow", "Singkatan dari Acknowlegment, merupakan paket dari TCP yang dikirimkan untuk menandakan bahwa permintaan diterima"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("MainWindow", "PSH"))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("MainWindow", "Sebuah paket dari TCP yang meminta untuk segera mengirimkan sebuah data kepada alamat penerima dengan mendorong data tersebut agar segera keluar dibandingkan dengan menunggu data lain keluar dari buffer"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("MainWindow", "URG"))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("MainWindow", "Sebuah paket dari TCP yang apabila dikirim menandakan bahwa paket tersebut bersifat urgensi dan harus diprioritaskan dalam pengirimannya. "))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("MainWindow", "RST"))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("MainWindow", "Merupakan sebuah paket TCP yang akan dikirimkan apabila ada sebuah paket TCP tiba-tiba datang ke perangkat. Perangkat tersebut biasanya akan mengirmkan sebuah paket reset ke jaringan yang sama"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("MainWindow", "FIN"))
        item = self.tableWidget.item(12, 1)
        item.setText(_translate("MainWindow", "Sebuah paket TCP yang biasanya digunakan untuk mengakhiri sebuah koneksi TCP. "))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("MainWindow", "Port"))
        item = self.tableWidget.item(13, 1)
        item.setText(_translate("MainWindow", "Titik akhir komunikasi yang digunakan untuk mengidentifikasi proses tertentu yang akan masuk ke perangkat melalui jaringan "))
        self.tableWidget.setSortingEnabled(__sortingEnabled)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Glosarium_Istilah()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
